### ISSUE TITLE
about the equation 5 and recursive knowledge distillation in paper

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [zma-c-137/VarGFaceNet#3]
hi @zma-c-137 
it is very fancy to see the results, but i have two questions:
1 the equation 5 in paper looks like a euclidean distance not cosine distance
2 how do recursive knowledge distillation do? can u give more details? it' seems that it is trianing using more iterations/epochs for the same student model.
thanks!

**Comment by yanmengjia** [comment]
Hi,
1. cosine distance is the equivalent of Euclidean distance when performing L2 normalization after embeddings.
2. If you training more iterations for same student model, momentum of SGD will be accumulated. We just use student model of first generation to initial the next generation, which 1. finds better local minimal, 2. relieves the generalization gap between the teacher model and  the student model.
