### ISSUE TITLE
missing a se block in head setting

### ISSUE THREAD

**Issue by TatsuyaShirakawa** [zma-c-137/VarGFaceNet#6]
It seems to have a se block at the end of branch in head setting (i.e. varg-conv1x1-varg-conv1x1-`se`) but it's not visualized in [the network diagram](https://github.com/zma-c-137/VarGFaceNet/raw/master/base_module.png).

![image](https://user-images.githubusercontent.com/11359334/68285798-484f4a00-00c3-11ea-83b8-98bd69fcb384.png)

More detailed network diagram is attached
[VargFaceNet.pdf](https://github.com/zma-c-137/VarGFaceNet/files/3813543/VargFaceNet.pdf)
which is created by the following code. 
```python
    net = get_symbol()
    digraph = mx.viz.plot_network(net, shape={'data': (1, 3, 112, 112)},
                                  node_attrs={'fixedsize': 'false'})
    digraph.view()
```

Thanks.

**Comment by zma-c-137** [comment]
yes, there is a se block at the end of head setting. Thank you for pointing out this mistake  and we will update our arxiv paper as well as this repo soon.
