### ISSUE TITLE
the teacher-student feature loss is negative?

### ISSUE THREAD

**Issue by HaoLiuHust** [zma-c-137/VarGFaceNet#8]
the equal 5 in your paper is negative, is that a mistake or by design?

**Comment by clhne** [comment]
what's equal 5 in the paper?

**Comment by HaoLiuHust** [comment]
Ls loss， 
[https://imgchr.com/i/MoOwmq](url)

**Comment by HaoLiuHust** [comment]
![企业微信截图_15743912329106](https://user-images.githubusercontent.com/7233091/69394675-a9a82780-0d17-11ea-92ca-6add5abae867.png)

**Comment by HaoLiuHust** [comment]
since it has "-" at the front, Ls is definitely negative

**Comment by yanmengjia** [comment]
Thanks for the notice.  It's a mistake, equal 5 should be a positive loss. We will update the paper soon.
